/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuSegundoProjetoJava;
import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);
        int numero1,numero2;
        String nome;        
        
        System.out.println("Digite o primeiro numero: ");
        numero1 = scan.nextInt();
        
        scan.nextLine();
        System.out.println("Digite seu nome: ");
        nome = scan.nextLine();
        
        System.out.println("Digite o segundo numero: ");
        numero2 = scan.nextInt();
        
        System.out.println(nome+" a soma e "+ (numero1+numero2));
        scan.close();
    }
}
