/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacegrafica;

import javax.swing.DefaultListModel;

/**
 *
 * @author LIVIAHELOISAALVESSOB
 */
public class PokemonExercicio extends javax.swing.JFrame {

    /**
     * Creates new form PokemonExercicio
     */
    Pokemon pok = new Pokemon("Genesect","Bug,Steel",100);
    Pokemon pok2 = new Pokemon("Giratina","Dragon,Ghost",90);
    Pokemon pok3 = new Pokemon("Necrozma","Psychic",80);
    Pokemon pok4 = new Pokemon("Golisopod","Bug,Water",50);
    Pokemon pok5 = new Pokemon("Bisharp","Dark,Steel",60);
    Pokemon pok6 = new Pokemon("Metagross","Psychic,Steel",65);
    Pokemon pok7 = new Pokemon("Aegislash","Ghost,Steel",70);
    Pokemon pok8 = new Pokemon("Garchomp","Dragon,Ground",75);
    DefaultListModel<String> modelo = new DefaultListModel<>();
    DefaultListModel<String> modelo2 = new DefaultListModel<>();
    public PokemonExercicio() {
        initComponents();
        listPC.setModel(modelo);
        modelo.addElement(pok.displayPokemon());
        modelo.addElement(pok2.displayPokemon());
        modelo.addElement(pok3.displayPokemon());
        modelo.addElement(pok4.displayPokemon());
        modelo.addElement(pok5.displayPokemon());
        modelo.addElement(pok6.displayPokemon());
        modelo.addElement(pok7.displayPokemon());
        modelo2.addElement(pok8.displayPokemon());
        listParty.setModel(modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPC = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listParty = new javax.swing.JList<>();
        titlePC = new javax.swing.JLabel();
        titleParty = new javax.swing.JLabel();
        buttonParty = new javax.swing.JButton();
        buttonPC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listPC);

        jScrollPane2.setViewportView(listParty);

        titlePC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titlePC.setText("PC");

        titleParty.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleParty.setText("Party");

        buttonParty.setText("Move to Party");
        buttonParty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPartyActionPerformed(evt);
            }
        });

        buttonPC.setText("Move to PC");
        buttonPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(titlePC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleParty)
                .addGap(96, 96, 96))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonParty, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPC, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titlePC)
                    .addComponent(titleParty))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonParty)
                    .addComponent(buttonPC))
                .addGap(204, 204, 204))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPCActionPerformed
        if(listParty.getModel().getSize() > 1){
            if(listParty.getSelectedIndex() != -1){
            modelo.addElement(listParty.getSelectedValue());
            modelo2.remove(listParty.getSelectedIndex());
        }
        }        
    }//GEN-LAST:event_buttonPCActionPerformed

    private void buttonPartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPartyActionPerformed
        if(listParty.getModel().getSize() < 6){
            if(listPC.getSelectedIndex() != -1){
                modelo2.addElement(listPC.getSelectedValue());
                modelo.remove(listPC.getSelectedIndex());
        }
        }
    }//GEN-LAST:event_buttonPartyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonExercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonExercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPC;
    private javax.swing.JButton buttonParty;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listPC;
    private javax.swing.JList<String> listParty;
    private javax.swing.JLabel titlePC;
    private javax.swing.JLabel titleParty;
    // End of variables declaration//GEN-END:variables
}
