/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacegrafica;

/**
 *
 * @author LIVIAHELOISAALVESSOB
 */
public class RadioButton extends javax.swing.JFrame {

    /**
     * Creates new form RadioButton
     */
    public RadioButton() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        buttonVelKoz = new javax.swing.JRadioButton();
        buttonKassadin = new javax.swing.JRadioButton();
        buttonMalzahar = new javax.swing.JRadioButton();
        buttonChoGath = new javax.swing.JRadioButton();
        buttonKaisa = new javax.swing.JRadioButton();
        buttonBelVeth = new javax.swing.JRadioButton();
        buttonKogMaw = new javax.swing.JRadioButton();
        buttonRekSai = new javax.swing.JRadioButton();
        text = new javax.swing.JLabel();
        text2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        title.setText("Choose your favorite Void Campion");

        buttonGroup1.add(buttonVelKoz);
        buttonVelKoz.setText("Vel'Koz");
        buttonVelKoz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVelKozActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonKassadin);
        buttonKassadin.setText("Kassadin");
        buttonKassadin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKassadinActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonMalzahar);
        buttonMalzahar.setText("Malzahar");
        buttonMalzahar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMalzaharActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonChoGath);
        buttonChoGath.setText("Cho'Gath");
        buttonChoGath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChoGathActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonKaisa);
        buttonKaisa.setText("Kaisa");
        buttonKaisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKaisaActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonBelVeth);
        buttonBelVeth.setText("Bel'veth");
        buttonBelVeth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBelVethActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonKogMaw);
        buttonKogMaw.setText("Kog'Maw");
        buttonKogMaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKogMawActionPerformed(evt);
            }
        });

        buttonGroup1.add(buttonRekSai);
        buttonRekSai.setText("Rek'Sai");
        buttonRekSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRekSaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonVelKoz)
                    .addComponent(buttonKassadin)
                    .addComponent(buttonMalzahar)
                    .addComponent(buttonChoGath))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonRekSai)
                    .addComponent(buttonKogMaw)
                    .addComponent(buttonBelVeth)
                    .addComponent(buttonKaisa))
                .addGap(126, 126, 126))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(text))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(text2)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVelKoz)
                    .addComponent(buttonKaisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKassadin)
                    .addComponent(buttonBelVeth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMalzahar)
                    .addComponent(buttonKogMaw))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonChoGath)
                    .addComponent(buttonRekSai))
                .addGap(87, 87, 87)
                .addComponent(text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(text2)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKogMawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKogMawActionPerformed
        text("How does it feel to have no passive?","Kog'Maw");        
    }//GEN-LAST:event_buttonKogMawActionPerformed

    private void buttonVelKozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVelKozActionPerformed
        text("You have good taste, just don't be weird about it","Vel'Koz");        
    }//GEN-LAST:event_buttonVelKozActionPerformed

    private void buttonKassadinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKassadinActionPerformed
        text("Suffer until level 16 and then make everyone else suffer","Kassadin");        
    }//GEN-LAST:event_buttonKassadinActionPerformed

    private void buttonMalzaharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMalzaharActionPerformed
        text("You are a simple Person","Malzahar");        
    }//GEN-LAST:event_buttonMalzaharActionPerformed

    private void buttonChoGathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChoGathActionPerformed
        text("Cool but try not to eat my house","Cho'Gath");              
    }//GEN-LAST:event_buttonChoGathActionPerformed

    private void buttonKaisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKaisaActionPerformed
        text("Just don't","Kaisa");
    }//GEN-LAST:event_buttonKaisaActionPerformed

    private void buttonBelVethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBelVethActionPerformed
        text("20000 dashes and a 10000 more on the way","Bel'Veth");
    }//GEN-LAST:event_buttonBelVethActionPerformed

    private void buttonRekSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRekSaiActionPerformed
        text("she is cool but never meta","Rek'Sai");
    }//GEN-LAST:event_buttonRekSaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButton().setVisible(true);
            }
        });
    }
    private void text(String tex,String cham){
        text.setText(tex);
        text2.setText("You have Chosen: "+cham);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton buttonBelVeth;
    private javax.swing.JRadioButton buttonChoGath;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton buttonKaisa;
    private javax.swing.JRadioButton buttonKassadin;
    private javax.swing.JRadioButton buttonKogMaw;
    private javax.swing.JRadioButton buttonMalzahar;
    private javax.swing.JRadioButton buttonRekSai;
    private javax.swing.JRadioButton buttonVelKoz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
